### PR TITLE
improved sendToZabbix.sh

### PR DESCRIPTION
**Pull request by Firewire2002**
The old script uses only one text item for all metrics in Zabbix. So it was impossible to generate graphs or statistics with it.
Now each value has it's own Zabbix item. :)

### CODE REVIEW

**Comment by JsBergbau** [comment]
Hi Firewire2002,
thanks for improving the Zabbix Callback. Can you please add a short mention for the new Zabbix Callback Readme in the main Readme, like there https://github.com/JsBergbau/MiTemperature2#send-metrics-to-prometheus 
Then I'll be happy to merge your pull request.

**Comment by Firewire2002** [comment]
Done and fixed the typo in Prometheus link description.

**Comment by JsBergbau** [comment]
Thanks for your work.

**Comment by szuro** [comment]
I'm a bit late to the part, but here I go:

> The old script uses only one text item for all metrics in Zabbix. So it was impossible to generate graphs or statistics with it. Now each value has it's own Zabbix item. :)

That was on purpose. The idea was to send all metrics in a single connection, and then extract data using preprocessing and dependant items.
Take a look at this crude template: https://gitlab.com/szuro/zabbix_templates/-/blob/master/Mi%20sensor%20%20LYWSD03MMC.yaml

**Comment by Firewire2002** [comment]
Yes that's also a nice way. But a single string isn't the best solution for such case. JSON would be the better way to transfer data in one shot. Much easier for parsing than a string.

**Comment by szuro** [comment]
Most certainly, JSON would be preferred, I just have an aversion to using it in bash scripts 😅

With one trapper item you only need to have one 'nodata' based trigger, which is always nice - preprocessing can be distributed across proxies, trigger evaluation cannot. 

I like how you handled the sender configuration ans PSK. Nicely done.

> Btw, my script uses also only one connection.

True that. I should never read code on a smartphone...

**Pull request merged**
